---
- name: deploy cups
  become: yes
  hosts: cups

  vars:

    tasks_cups_root_password: "12345678"
    tasks_cups_template_cups_listen: 192.168.8.43:631
    tasks_cups_template_cups_admin_networks: 
      - '192.168.8.0/24'

  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks
      vars:
        tasks_cups: true
