---
- name: deploy
  become: yes
  hosts: firstdc

  #### global vars
  vars:
    sambadc_realm: "smbdomain.local.br"

  #### tasks
  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks
      vars:
        tasks_common: true

    - name: configura /etc/hosts e /etc/hostnane
      include_role:
        name: Stouts.hostname
      vars:
        hostname_hostname: "{{ inventory_hostname }}.{{sambadc_realm}}"

    - name: Configura samba como um Domain Controller
      include_role:
        name: fflch.sambadc
      vars:
        sambadc_type: "new"
        sambadc_admin_password: "SuperSenh@1"
        sambadc_cups_server    : '192.168.8.43:631'
        sambadc_netbios        : "{{ inventory_hostname }}"
        sambadc_dns_forwarder: 8.8.8.8
        # Essa opção só deve ser ligada na primeira instalação
        sambadc_use_backports: false

    - name: Configura resolv.conf para consultar DNSs no próprio samba
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 192.168.8.48
        resolv_conf_search_domains:
          - "{{ sambadc_realm }}"
