---
- name: mariadbmaster
  become: yes
  hosts: mariadbmaster
     
  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks

    - name: Instala Mysql e cria dbs/users
      include_role:
        name: geerlingguy.mysql
      vars:
        mysql_root_username: root
        mysql_root_password: "SuperPassw0rd"
        mysql_bind_address: '*'
        mysql_mysqldump_max_allowed_packet: "1024M"
        mysql_users:
          - name: aegir_root
            host: "%"
            password: "SuperPassw0rd"
            priv: "*.*:ALL,GRANT"

          - name: zm
            host: "%"
            password: "SuperPassw0rd"
            priv: "zm.*:ALL"
            
          - name: freeradius
            host: "%"
            password: "freeradius"
            priv: "freeradius.*:ALL"

          - name: analytics
            host: "%"
            password: "analytics"
            priv: "analytics.*:ALL"

          - name: copaco
            host: "%"
            password: "copaco"
            priv: "copaco.*:ALL"

        mysql_databases:
           - name: zm
           - name: freeradius
           - name: analytics
           - name: copaco
