---
- name: deploy vagrant_nginxrevproxy
  become: yes
  hosts: nginxrevproxy

  vars:
    backup_directories:
      - /etc

    nginx_ssl_env: False
    nginx_revproxy_remove_webroot_sites: false
    nginx_revproxy_de_activate_sites: false

  tasks:

    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_nginxrevproxy: true
