---
- name: php8server 
  become: yes
  hosts: php8server
  vars:
    backup_directories:
      - /var/www
    backup_exclude_items:
      - vendor
      - node_modules

#### Preparação da máquina  
  tasks:
    - name: Aplica role fflch.tasks
      include_role:
        name: fflch.tasks
      vars:
        tasks_php: true
        tasks_php_version: '8.3'
        tasks_id_rsa: "{{ lookup('passwordstore', 'sti/tokens/ssh/fflch/private returnall=true') }}"
