---
- name: printers playbook
  hosts: printers
  become: yes

  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks

    - name: Configura resolv.conf para consultar DNSs do DC
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 192.168.8.48
        resolv_conf_search_domains:
          - "smbdomain.local.br"

    - name: fflch.printer-server
      include_role:
        name: fflch.printer-server
      vars:
        printer_server_cups_server: 192.168.8.43:631
        printer_server_realm: "smbdomain.local.br"
        printer_server_password: "SuperSenh@1"
        printer_server_use_backports: True

