---
- name: prolauno playbook
  hosts: proaluno
  become: yes

  tasks:

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks

    - name: proaluno role
      include_role:
        name: fflch.proaluno
      vars:
        proaluno_debian_version: "bookworm"
        proaluno_install_pacotes_debian: False
        proaluno_install_mate: True
        proaluno_ntp_servers:
          - 192.168.8.48
        proaluno_update_keys: False
        proaluno_sala: "proaluno_dev_"

    - name: Configura resolv.conf para consultar DNSs do firstdc dev
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 192.168.8.48
        resolv_conf_search_domains:
          - "smbdomain.local.br"

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        domain_member_realm: "smbdomain.local.br"
        domain_member_password: "SuperSenh@1"
