---
- name: prolauno playbook
  hosts: proaluno
  become: yes

  tasks:

#################### resolve o problema do grub no box generic/debian10
#    - name: Delete content & directory
#      file:
#        state: absent
#        path: /boot/grub/menu.lst
#
#    - name: Install a list of packages
#      apt:
#        force: yes
#        pkg:
#        - grub-legacy
####################

    - name: Aplica role fflch.tasks 
      include_role:
        name: fflch.tasks

    - name: proaluno role
      include_role:
        name: fflch.proaluno
      vars:
        proaluno_install_pacotes_debian: False
        proaluno_deploy_printers: True
        proaluno_install_mate: True
        proaluno_remove_all_printers: True
        proaluno_update_keys: True
        proaluno_cups_server: "ipp://192.168.8.43:631/printers"
        proaluno_sala: "proaluno_dev_"
        proaluno_ntp_servers:
          - 192.168.8.48
        proaluno_printers:
          - name: impressora
            device: "{{ proaluno_cups_server }}/financeiro_ppd"
            model: 'K7600_processado_gstopdf17.ppd'
          - name: pdfprinter
            device: "{{ proaluno_cups_server }}/pdfprinter"
            model: 'K7600_processado_gstopdf17.ppd'

    - name: Configura resolv.conf para consultar DNSs do firstdc dev
      include_role:
        name: blackstar257.resolv
      vars:
        resolv_conf_nameservers:
          - 192.168.8.48
        resolv_conf_search_domains:
          - "smbdomain.local.br"

    - name: fflch.domain-member
      include_role:
        name: fflch.domain-member
      vars:
        domain_member_realm: "smbdomain.local.br"
        domain_member_password: "SuperSenh@1"
