---
- name: projetos dev
  become: yes
  hosts: projetos

  vars:
    projetos_url: 'projetos.local.fflch.usp.br'
    backup_directories:
      - /var/www

  tasks:

    - name: Instalação do apache
      include_role:
        name: geerlingguy.apache
      vars:
        apache_remove_default_vhost: true
        #apache_options: "All"
        apache_options: "-Indexes +FollowSymLinks"
        apache_vhosts:
          - servername: "{{ projetos_url }}"
            serveralias: "www.{{projetos_url}}"
            documentroot: "/var/www/{{projetos_url}}"

    - name: clone repo
      git:
        repo: "https://github.com/fflch/projeto-humanidades-digitais.git"
        dest: "/var/www/{{projetos_url}}/humanidades-digitais"
        version: "master"
        force: yes
        update: yes

    - name: owner www-data
      file:
        path: "/var/www/"
        state: directory
        owner: www-data
        group: www-data
        recurse: yes

    - name: restart apache2
      service: name=apache2 state=restarted
